# Generated by Django 5.2.6 on 2025-10-02 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='El correo debe ser Gmail, Hotmail o Outlook(ej: usuario@gmail.com o usuario@hotmail.com).', regex='^[a-zA-Z0-9._%+-]+@(gmail\\.com|hotmail\\.com|outlook\\.com)$')]),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El número debe comenzar con +569 y tener 8 dígitos después (ej: +56912345678).', regex='^\\+569\\d{8}$')]),
        ),
    ]
